name: iban
description: A validation library for IBANs included in the official registry. Also supports some unofficial ones.
version: 0.2.0
authors:
- Christian Loitsch <christian@loitsch.com>
- Harm Aarts <harm@aarts.email>
homepage: https://github.com/close2/iban

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  mod97: '>=0.0.1 <1.0.0'

dev_dependencies:
  test: '>=0.12.0 <2.0.0'
  pedantic: ^1.8.0
